Repository FRONTENDSCHOOL7/final-05-oguogu, pull requests merged in 2023-10, with the labels that each got.

#4 ✨ Feat : 홈(피드) 페이지 팔로잉 없는 경우 화면 구현(#1)
  src/App.js
  src/assets/images/icon_ogudog_gray01.png
  src/components/common/header/Header.jsx
  src/components/common/header/Header.style.js
  src/components/common/navbar/NavBar.jsx
  src/components/common/navbar/NavBar.style.js
  src/components/home/NoneFeed.jsx
  src/components/home/NoneFeed.style.js
  src/pages/HomePage/HomePage.jsx
  src/router/AppRouter.jsx
  src/style/Global.style.js
Labels: ✨ 기능, 🎨 마크업

#6 🎨 Style : 글로벌스타일 파일명 변경 및 폰트재설정
  src/App.js
  src/style/GlobalStyle.js
Labels: 🎨 마크업

#8 ✨ Feat : REQ-021 채팅목록페이지 ChatPage 기능 구현(#2)
  src/App.js
  src/assets/images/icon_chat_ellipse.png
  src/assets/images/icon_chat_pink.png
  src/pages/ChatPage/ChatList.jsx
  src/pages/ChatPage/ChatPage.style.jsx
  src/pages/ChatPage/ChatRoom.jsx
  src/router/AppRouter.jsx
Labels: ✨ 기능, 🎨 마크업

#14 🎨 Style : 공통컴포넌트 UI(버튼,헤더) 타입과 사이즈별로 구현(#12)
  src/components/common/button/Button.jsx
  src/components/common/button/Button.style.jsx
  src/components/common/header/Header.jsx
  src/components/common/header/Header.style.js
  src/components/common/navbar/NavBar.jsx
  src/components/common/navbar/NavBar.style.js
  src/style/GlobalStyle.js
  src/style/index.css
Labels: ✨ 기능, 🎨 마크업

#20 ✨ Feat : api 인스턴스 및 메서드 추가
  src/api/axiosInstance.js
  src/api/image.api.js
  src/api/join.api.js
  src/api/login.api.js
  src/api/profile.api.js
Labels: ✨ 기능

#22 🐞 Fix : 스타일관련 콘솔 에러 수정
  src/api/image.api.js
  src/api/join.api.js
  src/api/login.api.js
  src/components/common/button/Button.style.jsx
  src/components/common/navbar/NavBar.jsx
  src/pages/ChatPage/ChatListPage.jsx
  src/pages/ChatPage/ChatPage.style.jsx
  src/pages/ChatPage/ChatRoomPage.jsx
  src/pages/JoinPage/JoinPage.jsx
  src/pages/LoginPage/EmailLoginPage.jsx
  src/pages/LoginPage/MainLoginPage.jsx
  src/router/AppRouter.jsx
Labels: 🐞 버그, ✨ 기능, 🎨 마크업

#24 ✨ Feat :REQ-021 채팅방
  src/assets/images/icon_chat_circle.svg
  src/pages/ChatPage/ChatListPage.jsx
  src/pages/ChatPage/ChatPage.style.jsx
  src/pages/ChatPage/ChatRoomPage.jsx
Labels: ✨ 기능, 🎨 마크업

#16 🎨 Style : 업로드 페이지 마크업 완료
  src/App.js
  src/components/common/header/Header.jsx
  src/pages/404/NotFoundPage.style.js
  src/pages/JoinPage/JoinPage.jsx
  src/pages/LoginPage/MainLoginPage.jsx
  src/pages/Upload/UploadPage.jsx
  src/pages/Upload/UploadPage.style.js
  src/router/AppRouter.jsx
Labels: ✨ 기능, 🙏 리뷰요청, 🎨 마크업

#30 ♻️ Refactor : 뒤로가기 버튼 헤더로부터 분리
  src/components/common/button/Button.jsx
  src/components/common/button/Button.style.jsx
  src/components/common/header/Header.jsx
  src/components/common/header/Header.style.js
Labels: ♻️ 리팩토링

#31 ✨ Feat : 이메일 로그인 마크업&기능구현
  src/components/login/Header.jsx
  src/components/login/Header.style.js
  src/hook/useValidation.js
  src/pages/LoginPage/EmailLoginPage.jsx
  src/pages/LoginPage/EmailLoginPage.style.js
Labels: ✨ 기능, 🎨 마크업

#32 ✨ Feat : 홈페이지 데이터처리 제외 구현 완료
  src/api/axiosInstance.js
  src/api/login.api.js
  src/api/post.api.js
  src/api/product.api.js
  src/components/common/button/Button.jsx
  src/components/common/button/Button.style.jsx
  src/components/common/container/Container.style.js
  src/components/common/header/Header.style.js
  src/components/common/navbar/NavBar.style.js
  src/components/home/FollowingFeed.jsx
  src/components/home/FollowingFeed.style.js
  src/components/post/PostCard.jsx
  src/components/post/PostCard.style.js
  src/components/post/PostList.jsx
  src/components/post/PostList.style.js
  src/components/product/ProductCard.style.js
  src/index.js
  src/pages/ChatPage/ChatPage.style.js
  src/pages/HomePage/HomePage.jsx
  src/pages/LoginPage/EmailLoginPage.jsx
  src/pages/Upload/UploadPage.jsx
  src/router/AccessRouter.jsx
  src/router/AppRouter.jsx
  src/style/index.css
Labels: ✨ 기능, 🎨 마크업, ♻️ 리팩토링

#37 ✨ Feat : 프로필,게시글작성 api 구현 + 포스트카드(게시글)에 데이터 대입
  src/api/image.api.js
  src/api/login.api.js
  src/api/post.api.js
  src/api/product.api.js
  src/api/profile.api.js
  src/atoms/navMenu.js
  src/components/comment/CommentList.jsx
  src/components/comment/CommentList.style.js
  src/components/comment/CommentWrite.jsx
  src/components/comment/CommentWrite.style.js
  src/components/common/navbar/NavBar.jsx
  src/components/home/FollowingFeed.jsx
  src/components/home/FollowingFeed.style.js
  src/components/post/PostCard.jsx
  src/components/post/PostCard.style.js
  src/components/post/PostGallery.jsx
  src/components/post/PostGallery.style.js
  src/components/post/PostList.jsx
  src/components/post/PostList.style.js
  src/components/product/ProductCard.jsx
  src/components/product/ProductList.jsx
  src/components/product/ProductList.style.js
  src/components/profile/Feed.jsx
  src/components/profile/Feed.style.js
  src/components/profile/ProfileBox.jsx
  src/components/profile/ProfileBox.style.js
  src/hook/useDebounce.js
  src/hook/useValidation.js
  src/index.js
  src/pages/ChatPage/ChatListPage.jsx
  src/pages/ChatPage/ChatPage.style.js
  src/pages/HomePage/HomePage.jsx
  src/pages/LoginPage/EmailLoginPage.jsx
  src/pages/PostDetailPage/PostDetailPage.jsx
  src/pages/PostDetailPage/PostDetailPage.style.js
  src/pages/PostUpload/PostUploadPage.jsx
  src/pages/PostUpload/PostUploadPage.style.js
  src/pages/ProfileMy/ProfileMy.jsx
  src/pages/ProfileMy/ProfileMy.style.js
  src/pages/ProfilePage/ProfilePage.jsx
  src/pages/ProfileYour/ProfileYour.jsx
  src/pages/ProfileYour/ProfileYour.style.js
  src/pages/Upload/UploadPage.style.js
  src/router/AppRouter.jsx
Labels: ✨ 기능, 🎨 마크업

#41 ✨ Feat : 게시글상세페이지-댓글작성기능구현
  src/api/comment.js
  src/api/join.api.js
  src/components/comment/CommentCard.jsx
  src/components/comment/CommentCard.style.js
  src/components/comment/CommentList.jsx
  src/components/comment/CommentList.style.js
  src/components/comment/CommentWrite.jsx
  src/components/comment/CommentWrite.style.js
  src/components/common/container/Container.style.js
  src/components/common/header/Header.jsx
  src/components/post/PostList.style.js
  src/components/profile/ProfileBox.style.js
  src/pages/LoginPage/EmailLoginPage.jsx
  src/pages/PostDetailPage/PostDetailPage.jsx
  src/pages/PostDetailPage/PostDetailPage.style.js
  src/pages/PostUpload/PostUploadPage.jsx
Labels: 🐞 버그, ✨ 기능, 🎨 마크업

#39 🎨 Style : 모달 마크업 및 기능
  src/api/post.api.js
  src/components/common/modal/ModalAlert.jsx
  src/components/common/modal/ModalAlert.style.js
  src/components/common/modal/Modalbottom.jsx
  src/components/common/modal/Modalbottom.style.js
  src/components/post/PostCard.jsx
  src/pages/ChatPage/ChatRoomPage.jsx
  src/pages/ProfileMy/ProfileMy.jsx
  src/pages/ProfilePage/ProfilePage.jsx
Labels: ✨ 기능, 🎨 마크업
