Repository FRONTENDSCHOOL7/final-05-oguogu, pull requests merged in 2023-11, with the labels that each got.

#48 ✨ Feat : 모달,컨펌 구현완료
  src/api/comment.api.js
  src/api/post.api.js
  src/api/product.api.js
  src/atoms/confirm.js
  src/atoms/modal.js
  src/components/comment/CommentCard.jsx
  src/components/comment/CommentList.jsx
  src/components/comment/CommentWrite.jsx
  src/components/common/header/Header.jsx
  src/components/common/modal/BottomModal.jsx
  src/components/common/modal/BottomModal.style.js
  src/components/common/modal/ConfirmModal.jsx
  src/components/common/modal/ConfirmModal.style.js
  src/components/common/modal/ModalAlert.jsx
  src/components/common/modal/ModalAlert.style.js
  src/components/common/modal/Modalbottom.jsx
  src/components/common/modal/Modalbottom.style.js
  src/components/follow/FollowCard.jsx
  src/components/follow/FollowList.jsx
  src/components/post/PostCard.jsx
  src/components/post/PostList.jsx
  src/components/product/ProductCard.jsx
  src/components/product/ProductList.jsx
  src/components/profile/Feed.jsx
  src/components/profile/ProfileBox.jsx
  src/hook/useConfirm.js
  src/hook/useModal.js
  src/pages/ChatPage/ChatRoomPage.jsx
  src/pages/FollowPage/FollowersPage.jsx
  src/pages/FollowPage/FollowingsPage.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/PostDetailPage/PostDetailPage.jsx
  src/pages/ProfileMy/ProfileMy.jsx
  src/pages/ProfilePage/ProfilePage.jsx
Labels: ✨ 기능, ♻️ 리팩토링

#47 ✨ Feat : 상품 등록 페이지
  src/api/product.api.js
  src/components/product/ProductCard.jsx
  src/components/profile/ProfileBox.jsx
  src/pages/AddProductPage/AddProductPage.jsx
  src/pages/AddProductPage/AddProductPage.style.js
  src/pages/ProductEditPage/ProductEditPage.jsx
  src/router/AppRouter.jsx
Labels: ✨ 기능, 🙏 리뷰요청, 🎨 마크업

#50 ✨ Feat : 무한스크롤 적용 및 추가기능구현
  src/api/comment.api.js
  src/api/heart.api.js
  src/api/post.api.js
  src/atoms/confirm.js
  src/atoms/modal.js
  src/components/comment/CommentList.jsx
  src/components/common/container/Container.style.js
  src/components/common/modal/BottomModal.jsx
  src/components/common/modal/BottomModal.style.js
  src/components/common/modal/ConfirmModal.jsx
  src/components/common/modal/ConfirmModal.style.js
  src/components/home/FollowingFeed.jsx
  src/components/post/PostCard.jsx
  src/components/post/PostList.style.js
  src/components/product/ProductList.jsx
  src/components/profile/Feed.jsx
  src/components/profile/Feed.style.js
  src/hook/useConfirm.js
  src/hook/useModal.js
  src/hook/useObserve.js
  src/pages/AddProductPage/AddProductPage.jsx
  src/pages/AddProductPage/AddProductPage.style.js
  src/pages/HomePage/HomePage.jsx
  src/pages/PostDetailPage/PostDetailPage.jsx
  src/pages/ProductEditPage/ProductEditPage.jsx
Labels: ✨ 기능

#52 🐞 Fix : 프로필 이미지 업로드 버튼 움직임 버그 해결 및 포인터커서 설정
  src/pages/JoinPage/ProfileForm.style.js
Labels: 🐞 버그

#55 🐞 Fix : 프로필설정 유효성검사에러메시지 및 프로필이미지 설정 시 발생하는 버그 수정
  src/components/login/Header.jsx
  src/hook/useUserForm.js
  src/pages/JoinPage/ProfileForm.jsx
  src/pages/JoinPage/ProfileForm.style.js
Labels: 🐞 버그

#58 ✨ Feat : MyProfile에서 프로필수정 버튼 클릭 시 프로필수정페이지로 이동
  src/components/profile/ProfileBox.jsx
  src/pages/ProfileEditPage/ProfileEditPage.jsx
  src/router/AppRouter.jsx
Labels: ✨ 기능, 🎨 마크업

#54 ✨ Feat : 게시글 수정 페이지
  src/pages/PostEditPage/PostEditPage.jsx
  src/router/AppRouter.jsx
Labels: ✨ 기능, 🙏 리뷰요청

#61 ✨ Feat : 로더 구현
  src/assets/images/icon_loader.svg
  src/components/common/loader/Loader.jsx
  src/components/home/FollowingFeed.jsx
  src/components/home/FollowingFeed.style.js
  src/components/post/PostList.jsx
  src/components/post/PostList.style.js
  src/components/product/ProductList.jsx
  src/components/profile/Feed.jsx
  src/components/profile/Feed.style.js
  src/components/profile/ProfileBox.jsx
  src/components/profile/ProfileBox.style.js
  src/pages/HomePage/HomePage.jsx
Labels: ✨ 기능, 🎨 마크업

#67 ✨ Feat : 게시글 수정 페이지 완료
  src/api/post.api.js
  src/pages/PostEditPage/PostEditPage.jsx
  src/pages/PostUpload/PostUploadPage.jsx
  src/router/AppRouter.jsx
Labels: ✨ 기능, 🎨 마크업

#60 ♻️ Refactor : 프로필수정페이지 생성을 위한 리팩토링
  src/api/profile.api.js
  src/components/join/EmailPwPage.jsx
  src/components/join/EmailPwPage.style.js
  src/components/join/ProfileForm.jsx
  src/components/join/ProfileForm.style.js
  src/pages/JoinPage/JoinPage.jsx
  src/pages/JoinPage/ProfileSettingPage.jsx
  src/pages/JoinPage/ProfileSettingPage.style.js
  src/pages/ProfileEditPage/ProfileEditPage.jsx
Labels: ✨ 기능, 🎨 마크업, ♻️ 리팩토링

#66 Feature/splash animation hyeji
  src/assets/images/logo_ogu_01.png
  src/assets/images/logo_ogu_03.png
  src/assets/images/logo_ogu_gu1.png
  src/assets/images/logo_ogu_o1.png
  src/assets/images/logo_ogu_o2.png
  src/assets/images/logo_oguogu_white.png
  src/pages/LoginPage/MainLoginPage.style.js
  src/pages/SplashPage/SplashPage.jsx
  src/pages/SplashPage/SplashPage.style.js
Labels: ✨ 기능, 🎨 마크업

#68 ✨ Feat : 판매상품페이지 구현
  src/api/profile.api.js
  src/components/comment/CommentList.jsx
  src/components/common/button/Button.style.js
  src/components/common/header/Header.jsx
  src/components/home/FollowingFeed.jsx
  src/components/post/PostCard.jsx
  src/components/post/PostList.jsx
  src/components/product-page/ProductItem.jsx
  src/components/product-page/ProductSection.jsx
  src/components/product-page/ProductSection.style.js
  src/components/product/ProductCard.style.js
  src/components/product/ProductList.jsx
  src/components/product/ProductList.style.js
  src/components/profile/Feed.jsx
  src/pages/ChatPage/ChatRoomPage.jsx
  src/pages/FollowPage/FollowersPage.jsx
  src/pages/FollowPage/FollowingsPage.jsx
  src/pages/PostEditPage/PostEditPage.jsx
  src/pages/ProductPage/AllProductPage.jsx
  src/pages/ProductPage/UserProductPage.jsx
  src/router/AppRouter.jsx
Labels: ✨ 기능, 🎨 마크업

#73 리다이렉트 문서 등록
  public/_redirects
Labels: 🌐 배포
